import Head from 'next/head';
import Link from 'next/link';
import { useState, useEffect } from 'react';
import styles from '../styles/Home.module.css';
export default function Home() {
	const [data, setData] = useState([]);
	useEffect(() => {
		const a = async () => {
			try {
				const res = await fetch('/api/books');
				const data = await res.json();
				console.log(data);
				setData(data);
			} catch (err) {
				console.log(err);
			}
		};
		a();
	}, []);

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header>
				<p>🎀</p>
				<Link href="/info">
					<a>Info</a>
				</Link>
			</header>
			<main>
				<div className="book-article">
					{/* {console.log(data)} */}

					{data.map((el) => (
						<Link href={`/book/${el.id}`} key={el.id}>
							<a>{el.title}</a>
						</Link>
					))}
					<p>title</p>
					<span>author</span>
				</div>
			</main>
			<footer>asdsad</footer>
		</div>
	);
}
