import Head from 'next/head';
import Link from 'next/link';
import { useState, useEffect } from 'react';
import home from '../styles/home.module.css';
import GalleryImage from '../components/GalleryImage';
import Image from 'next/image';

export default function Home() {
	const [data, setData] = useState([]);
	useEffect(() => {
		const a = async () => {
			try {
				const res = await fetch('/api/books');
				const data = await res.json();

				setData(data);
			} catch (err) {
				console.log(err);
			}
		};
		a();
	}, []);

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={home.galleryWrapper}>
				{data.map(({ id, title, author, poster }) => (
					<Link href={`/book/${id}`} key={id}>
						<a>
							<GalleryImage title={title} author={author} poster={poster} />
						</a>
					</Link>
				))}
			</div>
		</div>
	);
}
